[phases.setup]
   nixPkgs = ["nodejs_22", "corepack_22"]

[phases.install]
   cmds = [
     "COREPACK_INTEGRITY_KEYS=0 pnpm store prune",
     "COREPACK_INTEGRITY_KEYS=0 corepack prepare pnpm@latest --activate",
     "pnpm install"
   ]

[phases.build]
   cmds = ["pnpm run build:prod"]

[start]
   cmd = "pnpm run build:start"
